#!/usr/bin/env sh

set -e

cd core
cabal sandbox init
cabal install --only-dependencies -j
cd -

mkdir ./.cabal-sandbox

for service in receiver mailer servant; do
  cd "$service"
  cabal sandbox init --sandbox ../.cabal-sandbox
  cabal sandbox add-source ../core
  ln -s ../conf shared.conf
  cabal install --only-dependencies -j
  cd -
done

for service in receiver web; do
  cd "$service"
  cabal sandbox add-source ../servant
  cd -
done
