#!/usr/bin/env sh

set -e

for lib in core mailer; do
  cd "$lib"
  cabal sandbox init
  cabal install --only-dependencies -j
  cd -
done

mkdir ./.cabal-sandbox

for service in receiver sender servant; do
  cd "$service"
  cabal sandbox init --sandbox ../.cabal-sandbox
  cabal sandbox add-source ../core
  ln -s ../conf shared.conf
  cabal install --only-dependencies -j
  cd -
done

for service in sender; do
  cd "$service"
  cabal sandbox add-source ../mailer
  cd -
done

for service in receiver web; do
  cd "$service"
  cabal sandbox add-source ../servant
  cd -
done
